apiVersion: v1
data:
  application.properties: |
    spring.data.mongodb.host=wherefore-mongodb-release
    spring.data.mongodb.port=27017
    spring.data.mongodb.database=wfat
    spring.data.mongodb.username=${MONGODB_USERNAME}
    spring.data.mongodb.password=${MONGODB_PASSWORD}
kind: ConfigMap
metadata:
  name: api-springboot
  namespace: default
