apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app-deployment
  labels:
    app: angular-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
      - name: angular-app
        image: angular-app:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: application-config
          mountPath: /usr/share/nginx/html/assets/config/config.production.json
          subPath: config.production.json
      volumes:
      - name: application-config
        configMap:
          name: angular-app

        