apiVersion: v1
data:
  appsettings.json: |+
    {
      "CandidateDatabaseSettings": {
        "CollectionName": "candidates",
        "ConnectionString": "mongodb://wherefore-release-mongodb:27017",
        "DatabaseName": "wfat"
      },
      "Logging": {
        "IncludeScopes": false,
        "Debug": {
          "LogLevel": {
            "Default": "Warning"
          }
        },
        "Console": {
          "LogLevel": {
            "Default": "Warning"
          }
        }
      }
    }
kind: ConfigMap
metadata:
  name: api-dotnet
  namespace: default